### ISSUE TITLE
Content updates

### ISSUE THREAD

**Issue by atreni** [JustFixNYC/tenants#123]
1. Status update - change to: "Add a status update!"
2. PDF letter:
      - change CTA to: "Preview letter"
      - change CTA after generation to: "View letter" and "Close" (*both should save the link to the Case History page!)

**Comment by romeboards** [comment]
![screen shot 2016-08-12 at 6 47 09 pm](https://cloud.githubusercontent.com/assets/627751/17639105/3bd9d910-60bd-11e6-82af-ff95405beac6.png)
