### ISSUE TITLE
Tutorial / FAQ page

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/tenants#150]
Possibly multiple pages depending on amount of content
Annotated images for how-to

**Comment by romeboards** [comment]
-Linked vs. Managed Accounts
-How to organize w/ JF

**Comment by atreni** [comment]
Work in progress: https://docs.google.com/a/justfix.nyc/document/d/176QWBJB6nh_Y5iHsc4FG5Idyr_vGFxwabFmJSt-FUDI/edit?usp=sharing
