### ISSUE TITLE
New Case History / share view

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/tenants#152]
@atreni any design considerations on the tab view?

**Comment by romeboards** [comment]
Cross reference with print functionality.... @Meegan

**Comment by atreni** [comment]
![case history tabs](https://cloud.githubusercontent.com/assets/7797826/22628867/b45a0bd6-eba9-11e6-9fee-0e4ea2a92490.jpg)
![public view tabs](https://cloud.githubusercontent.com/assets/7797826/22628868/b45c9068-eba9-11e6-98f0-32a037fdef6b.jpg)
