### ISSUE TITLE
Add a "copy share URL" link to dashboard items

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/tenants#155]
@atreni design considerations????????

https://clipboardjs.com/

**Comment by atreni** [comment]
![shared desktop](https://cloud.githubusercontent.com/assets/7797826/22337555/3cefc1d8-e3b3-11e6-8074-63cde6095ccb.png)
![shared mobile](https://cloud.githubusercontent.com/assets/7797826/22337556/3cf26712-e3b3-11e6-90ba-7aa3bf4cb35c.jpg)

**Comment by atreni** [comment]
![dashboard home](https://cloud.githubusercontent.com/assets/7797826/22628670/36b83c96-eba6-11e6-83af-3b18d9aa6d4b.png)

**Comment by romeboards** [comment]
@atreni we should talk about placement on the detail pages here
