### ISSUE TITLE
Know Your Rights section 

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/tenants#57]
How best to manage content???

**Comment by atreni** [comment]
1. Missing a period after "more" on the index page.
2. Read More CTA - should only be on: Am I rent stabilized? Starting an HP Action, Responding to Nonpayment..., Creating a TA. **Currently appears on all even when not needed.**
3. Increase the URL size - should be 16 pt, with 24 leading
4. Links should open new page
5. Formatting - add spaces between paragraphs of text
6. Wrong links - "Creating a tenant association" - only use MetCouncil link (the other 2 are for the Tenant harassment section)
7. Take action and Find Help - should be right above footer. Remove grey space between.

**Comment by romeboards** [comment]
- Use global link style (see core.scss)
- Back button should always go back to the list view - mess with window.history in the stateChange provider

**Comment by atreni** [comment]
update right chevron on index page (should be the same as edit profile chevrons)

**Comment by atreni** [comment]
check the names of the links in content doc (in addition to updating styling)

**Comment by atreni** [comment]
Update "Got it" button on disclaimer to be btn-block

**Comment by atreni** [comment]
Individual pages - white background - See updated JPGs

**Comment by Meegan** [comment]
@romeboards Header seems to have an additional margin on mobile, should this come out?

**Comment by atreni** [comment]
- Got it button on disclaimer - btn-block (180pt width)
- Add numbers to "Want to know more" links
- Increase leading on all "Want to know more" links to 24pt (external links)
- Want to know more links ALL need break line between them (on every page that has more than one link)
- “Read more” button on desktop - too wide
- Increase next and previous links (at bottom) to 16pt

**Individual pages:**
Am I rent stabilized:
- “Email through JustFix.nyc” - link to Take Action section
- "Or visit DHCR website" (in body text) - link should be Green link style
- Fix text: MetCouncil on housing: Rent stabilized leases

Starting an HP Action:
- Tip! - blue background #0E6594

Responding to a Nonpayment Eviction proceeding:
- Make small “a” in title

Creating a tenant association:
- Add link - CASA: Why form a tenant association? (links to https://nsacasa.files.wordpress.com/2014/08/why-form-a-ta.pdf)

**Comment by atreni** [comment]
- KYR main page - right chevrons should be centered with text (seem off)
- First chevron is still bold for some reason?
