### ISSUE TITLE
Profile pages

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/tenants#60]
Show profile "view" page
Forgot password - need to figure out how best to handle this since the user doesn't enter their email address....

**Comment by atreni** [comment]
Width of container for all "Edit" views

**Comment by atreni** [comment]
Sign out button - adjust width to "btn-block"

**Comment by Meegan** [comment]
Validation for PW

**Comment by atreni** [comment]
1. Make tenant info + organizer info regular font weight. Keep "Advocate information" in semibold
2. Edit profile, change phone number, change password pages - align title to left. Remove "your" from each title
3. Change password page: change "verify password" help text to "confirm password"
4. Change phone number page: change "Change phone" title to "Change phone number". change "verify" CTA to "Continue"
5. Change phone number page 2: remove auto populate of current phone number

**Comment by atreni** [comment]
- Still auto populates phone number on change phone number screen (see issue #105)
- Change password page - remove "Confirm your password" large title; should just be in the help text in second box
- Can we have a confirmation that information has been saved on the main profile page after selecting save? @romeboards default bootflat green confirmation?

**Comment by atreni** [comment]
Make Advocate phone number and email under profile links to call and email!
