### ISSUE TITLE
Front-end for Letter of complaint 

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/tenants#62]

**Comment by romeboards** [comment]
"Add details" text needs to go away on completion (not hard refresh) - update user model on front end

**Comment by romeboards** [comment]
"Allinitial" needs to go away if you add a new thing to the checklist

**Comment by romeboards** [comment]
@atreni lets talk about error state for this

**Comment by romeboards** [comment]
Needs datepicker for access dates (see #75)

**Comment by atreni** [comment]
**Need a way to cxl or stop letter generation if the service is down!**

Small content changes:
- "Make sure to Add Details (located above)..."
- Inside card: "Mail an official...." (says Mail on collapsed card and Send on inside card)

**Comment by atreni** [comment]
Add more spacing before +Access date (kinda hard to click right now)
