### ISSUE TITLE
Implement email button on share controls

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/tenants#78]

**Comment by atreni** [comment]
👍

**Comment by atreni** [comment]
Share by email and text have a generic URL (http://beta.justfix.nyc/share/), not the specific case.... for only certain accounts that have been made (specifically during testing on 7/17/16)

**Comment by atreni** [comment]
Also - just talking with Georges; for our use case with tenants working with organizers - he agrees with you that advocate contact information should be auto populated on email + text under Case History. (but for general use case, not) Let me know if you have a question about this!
