### ISSUE TITLE
Tutorial!

### ISSUE THREAD

**Issue by atreni** [JustFixNYC/tenants#87]
See JPGS in 2 hours...
UI Bootstrap Carousel

**Comment by atreni** [comment]
I switched up the order: (updated JPGs on dropbox)
1. Intro "take the tour"
2. Gather evidence
3. Status update
4. Case history
5. Know your rights

**Comment by atreni** [comment]
1. Please make spacing under the bottom navigation and the footer 100px (currently 50)
2. The images look super low res - what do you need from me in order to make them better res?
3. Is the bottom half white? it looks grey to me - or maybe I'm crazy....

**Comment by atreni** [comment]
see new JPGs for arrow placement change! thank you so much!

**Comment by atreni** [comment]
Sorry Matt! Please update #4 - KYR PNG (it's updated in the dropbox)
Status Update and Share your Case PNGs aren't loading
Move progress dots + Got It! CTA closer to text - they are below the break on mobile (decrease padding by half?)

**Comment by atreni** [comment]
Still taking a while to load, and not all images are loading fully

**Comment by Meegan** [comment]
@atreni suggestions: 
  - Smaller image sizes
  - Image preloader

Not getting missing images, however?
